<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINPUNW039D" failures="0" tests="10" name="TestAutomation.testng.exception.TestLibrary" time="0.028" errors="0" timestamp="2022-02-12T23:10:10 IST" skipped="0">
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="displayingNumbers" time="0.002"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="displayingNumbers" time="0.002"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="testAddMembers" time="0.001"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="testAddMembers" time="0.004"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="testaddMember" time="0.003"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="displayingNumbers" time="0.001"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="displayingNumbers" time="0.001"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="displayingNumbers" time="0.010"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="testaddMember1" time="0.001"/>
  <system-out/>
  <testcase classname="TestAutomation.testng.exception.TestLibrary" name="testAddMembers" time="0.003"/>
  <system-out/>
</testsuite> <!-- TestAutomation.testng.exception.TestLibrary -->
